# Generated by Django 2.0.7 on 2018-07-30 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(null=True)),
                ('free', models.FloatField(null=True)),
                ('locked', models.FloatField(null=True)),
                ('cost_price', models.FloatField(default=0, null=True)),
                ('cost', models.FloatField(default=0, null=True)),
                ('market_value', models.FloatField(default=0, null=True)),
                ('profit_and_loss', models.FloatField(default=0, null=True)),
                ('p_a_l_percent', models.FloatField(default=0, null=True)),
                ('data_update_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('change_24h', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField()),
                ('logo', models.ImageField(blank=True, default='AssetLogo/default/default.png', upload_to='AssetLogo')),
                ('data_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DepositDetails',
            fields=[
                ('amount', models.FloatField()),
                ('address', models.CharField(max_length=100)),
                ('addressTag', models.CharField(max_length=100, null=True)),
                ('txId', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('insertTime', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Asset')),
            ],
        ),
        migrations.CreateModel(
            name='SymbolInfo',
            fields=[
                ('symbol', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('baseAssetPrecision', models.SmallIntegerField()),
                ('quotePrecision', models.SmallIntegerField()),
                ('baseAsset', models.CharField(max_length=100)),
                ('quoteAsset', models.CharField(max_length=100)),
                ('minPrice', models.FloatField()),
                ('maxPrice', models.FloatField()),
                ('tickSize', models.FloatField()),
                ('minQty', models.FloatField()),
                ('maxQty', models.FloatField()),
                ('stepSize', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('data_update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticker24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, null=True)),
                ('askPrice', models.FloatField()),
                ('bidPrice', models.FloatField()),
                ('askQty', models.FloatField()),
                ('bidQty', models.FloatField()),
                ('lastQty', models.FloatField()),
                ('firstId', models.CharField(max_length=10)),
                ('lastId', models.CharField(max_length=10)),
                ('openPrice', models.FloatField()),
                ('lowPrice', models.FloatField()),
                ('highPrice', models.FloatField()),
                ('lastPrice', models.FloatField()),
                ('volume', models.FloatField()),
                ('quoteVolume', models.FloatField()),
                ('priceChange', models.FloatField()),
                ('priceChangePercent', models.FloatField()),
                ('count', models.FloatField()),
                ('prevClosePrice', models.FloatField()),
                ('weightedAvgPrice', models.FloatField()),
                ('openTime', models.DateTimeField()),
                ('closeTime', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='asset',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.Asset'),
        ),
    ]
