# Generated by Django 2.0.7 on 2018-07-30 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CancelStandbyOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('clientOrderId', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('origQty', models.FloatField()),
                ('executedQty', models.FloatField()),
                ('status', models.CharField(max_length=100)),
                ('order_type', models.CharField(default='', max_length=100)),
                ('side', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('isWorking', models.BooleanField(default=True)),
                ('order_price', models.FloatField(default=0)),
                ('parent_order', models.CharField(max_length=100, null=True)),
                ('alter_time', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Qtrading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_name', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('amount', models.FloatField()),
                ('q_income', models.FloatField()),
                ('q_amount', models.FloatField()),
                ('h_price', models.FloatField()),
                ('l_price', models.FloatField()),
                ('iswork', models.BooleanField(default=True)),
                ('total_account', models.FloatField()),
                ('this_price', models.FloatField()),
                ('simulation_full', models.FloatField(null=True)),
                ('relatively_empty', models.FloatField(null=True)),
                ('quantitative_i', models.FloatField(null=True)),
                ('actual_i', models.FloatField(null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.SymbolInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('trade_id', models.IntegerField(primary_key=True, serialize=False)),
                ('price', models.FloatField()),
                ('qty', models.FloatField()),
                ('commission', models.FloatField()),
                ('commissionAsset', models.CharField(max_length=100)),
                ('time', models.DateTimeField()),
                ('isbuyer', models.BooleanField()),
                ('isMaker', models.BooleanField(default=True)),
                ('isBestMatch', models.BooleanField(default=True)),
                ('executed_price', models.FloatField()),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtrading.Order')),
                ('q_trading', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qtrading.Qtrading')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='q_trading',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='qtrading.Qtrading'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='currencies.SymbolInfo'),
        ),
        migrations.AddField(
            model_name='cancelstandbyorders',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qtrading.Order'),
        ),
    ]
